services:
  - type: web
    name: triangle
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: TURSO_DATABASE_URL
        value: libsql://triangle-search-triangle-search.aws-ap-southeast-2.turso.io
      - key: TURSO_AUTH_TOKEN
        value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3OTE0ODgyOTQsImlkIjoiMDFhMTFjZmYtYWMwMS03NjZjLThjZjUtYmVhYTM4NWQxNTQ2Iiwia2lkIjoiRUdaeGxicFhLdUpjem85RkVBcFBhVVN5ems2a0dVcTlxc3NfNzlqd1dUVSIsInJpZCI6ImE0NTBlMTAxLTZhNTUtNDc3Zi05MjI0LWEwZWNlOTQxODc5NiJ9.ew0u8RMGKOfAhrMIaCoPFtT9XlhCCYnnPsB3Bbyqm07srFgnT9yaajEM8TAk8rMS07CuqJSK6PpVea9QOJLZAA
